import { Asset } from './types';

export const INITIAL_ASSETS: Asset[] = [
  {
    id: 'FOOLAD',
    enName: 'Mobarakeh Steel',
    faName: 'فولاد مبارکه',
    category: 'metals',
    price: 0.082,
    change: 2.4,
    flag: 'ir',
    locationEn: 'Isfahan, Iran',
    locationFa: 'اصفهان، ایران',
    progress: 82
  },
  {
    id: 'FMILI',
    enName: 'National Copper',
    faName: 'ملی مس ایران',
    category: 'metals',
    price: 0.115,
    change: 1.8,
    flag: 'ir',
    locationEn: 'Kerman, Iran',
    locationFa: 'کرمان، ایران',
    progress: 91
  },
  {
    id: 'ZOB',
    enName: 'Zob Ahan Isfahan',
    faName: 'ذوب آهن اصفهان',
    category: 'metals',
    price: 0.041,
    change: -1.2,
    flag: 'ir',
    locationEn: 'Isfahan, Iran',
    locationFa: 'اصفهان، ایران',
    progress: 64
  },
  {
    id: 'KHODRO',
    enName: 'Iran Khodro',
    faName: 'ایران خودرو',
    category: 'auto',
    price: 0.045,
    change: -0.5,
    flag: 'ir',
    locationEn: 'Tehran, Iran',
    locationFa: 'تهران، ایران',
    progress: 73
  },
  {
    id: 'SAIPA',
    enName: 'Saipa Group',
    faName: 'سایپا',
    category: 'auto',
    price: 0.035,
    change: -0.8,
    flag: 'ir',
    locationEn: 'Tehran, Iran',
    locationFa: 'تهران، ایران',
    progress: 58
  },
  {
    id: 'KHGHOSTAR',
    enName: 'Gostar Auto',
    faName: 'گسترش خودرو',
    category: 'auto',
    price: 0.062,
    change: 1.1,
    flag: 'ir',
    locationEn: 'Tabriz, Iran',
    locationFa: 'تبریز، ایران',
    progress: 49
  },
  {
    id: 'SHAPOUR',
    enName: 'Bandar Imam Petrochemical',
    faName: 'پتروشیمی بندر امام',
    category: 'petro',
    price: 0.210,
    change: 3.5,
    flag: 'ir',
    locationEn: 'Mahshahr, Iran',
    locationFa: 'ماهشهر، ایران',
    progress: 88
  },
  {
    id: 'PARSAN',
    enName: 'Parsian Oil & Gas',
    faName: 'نفت و گاز پارسیان',
    category: 'petro',
    price: 0.185,
    change: 0.4,
    flag: 'ir',
    locationEn: 'Tehran, Iran',
    locationFa: 'تهران، ایران',
    progress: 70
  },
  {
    id: 'WEBMELAT',
    enName: 'Bank Mellat',
    faName: 'بانک ملت',
    category: 'bank',
    price: 0.060,
    change: 1.5,
    flag: 'ir',
    locationEn: 'Tehran, Iran',
    locationFa: 'تهران، ایران',
    progress: 95
  },
  {
    id: 'TEJARAT',
    enName: 'Bank Tejarat',
    faName: 'بانک تجارت',
    category: 'bank',
    price: 0.032,
    change: -0.2,
    flag: 'ir',
    locationEn: 'Tehran, Iran',
    locationFa: 'تهران، ایران',
    progress: 62
  },
  {
    id: 'GOLD',
    enName: 'Standard Gold Reserve',
    faName: 'ذخیره شمش طلای استاندارد',
    category: 'commodities',
    price: 1200.00,
    change: 18.2,
    flag: 'ch',
    locationEn: 'Zurich, Switzerland',
    locationFa: 'زوریخ، سوئیس',
    progress: 40
  },
  {
    id: 'JUMEIRAH',
    enName: 'Jumeirah Beach Villa',
    faName: 'ویلا ساحلی جمیرا',
    category: 'real_estate',
    price: 250.00,
    change: 9.5,
    flag: 'ae',
    locationEn: 'Dubai, UAE',
    locationFa: 'دبی، امارات',
    progress: 82
  },
  {
    id: 'LONDON_RE',
    enName: 'London Luxury Office',
    faName: 'ساختمان اداری لندن',
    category: 'real_estate',
    price: 550.00,
    change: 6.4,
    flag: 'gb',
    locationEn: 'London, UK',
    locationFa: 'لندن، انگلستان',
    progress: 61
  },
  {
    id: 'AAPL',
    enName: 'Apple Inc.',
    faName: 'اپل',
    category: 'global',
    price: 185.50,
    change: 1.2,
    flag: 'us',
    locationEn: 'California, USA',
    locationFa: 'کالیفرنیا، آمریکا',
    progress: 99
  },
  {
    id: 'TSLA',
    enName: 'Tesla Inc.',
    faName: 'تسلا',
    category: 'global',
    price: 210.00,
    change: -2.4,
    flag: 'us',
    locationEn: 'Texas, USA',
    locationFa: 'تگزاس، آمریکا',
    progress: 99
  }
];

export const TRANSLATIONS = {
  en: {
    appName: 'AssetChain',
    tagline: 'Real World Asset Tokenization Platform',
    statusConnected: 'Mainnet Connected',
    connectWallet: 'Connect Wallet',
    disconnectWallet: 'Disconnect Wallet',
    assetsMarket: 'Assets Market',
    portfolio: 'Portfolio',
    wallet: 'Wallet',
    history: 'History',
    support: 'Support',
    aboutUs: 'About Us',
    contactUs: 'Contact Us',
    signIn: 'Sign In',
    signOut: 'Sign Out',
    signUp: 'Sign Up',
    usernameOrEmail: 'Username or Email',
    password: 'Password',
    loginError: 'Invalid credentials. Use demo / 1234',
    noAccount: "Don't have an account? Sign Up",
    hasAccount: 'Already have an account? Sign In',
    allMarkets: 'All Markets',
    categoryMetals: 'Metals',
    categoryAuto: 'Automotive',
    categoryPetro: 'Petrochemical',
    categoryBank: 'Banking',
    categoryGlobal: 'Global Shares',
    categoryRealEstate: 'Real Estate',
    categoryCommodities: 'Gold & Commodities',
    statTvl: 'Total Value Locked (TVL)',
    statApy: 'Average APY',
    statSold: 'Assets Sold',
    topInvestment: 'Top Investment Opportunities',
    tokenPrice: 'Token Price',
    expectedYield: 'Expected Growth / APY',
    saleProgress: 'Sale Progress',
    remainingUnits: 'Remaining Units',
    viewDetails: 'View Details',
    buyNow: 'Quick Buy',
    buy: 'Buy',
    sell: 'Sell',
    myPortfolio: 'My Portfolio',
    totalBalance: 'Total Assets Balance',
    totalPnl: 'Total PnL',
    recentMonth: 'Last Month',
    pnlLabel: 'PnL',
    avgCost: 'Avg Price:',
    currentPrice: 'Current Price:',
    depositUsdt: 'Deposit USDT',
    withdrawUsdt: 'Withdraw USDT',
    transactionWarning: 'All transactions are processed securely and may take up to 24h to verify.',
    selectNetwork: 'Select Network',
    depositAddress: 'Deposit Address',
    txidLabel: 'Transaction Hash (TxID)',
    txidPlaceholder: 'Paste TxID here...',
    submitDeposit: 'Submit Deposit',
    depositSuccess: 'Deposit TxID submitted! Awaiting 24h verification.',
    destinationAddress: 'Destination Address',
    destinationPlaceholder: 'Enter wallet address...',
    amountUsdt: 'Amount (USDT)',
    minAmount: 'Min 10 USDT',
    requestWithdraw: 'Request Withdraw',
    withdrawSuccess: 'Withdrawal requested! Processing within 24h.',
    transactionHistory: 'Transaction History',
    thType: 'Type & Asset',
    thAmount: 'Amount',
    thDate: 'Date',
    thStatus: 'Status',
    statusCompleted: 'Completed',
    statusPending: 'Pending',
    supportCenter: 'Support Center',
    describeIssue: 'Describe your issue',
    howCanHelp: 'How can we help you?',
    submitTicket: 'Submit Ticket',
    ticketSuccess: 'Ticket {num} submitted successfully! We will respond within 72 hours.',
    confirmBuy: 'Confirm Buy Order',
    amountToInvest: 'Amount to Invest (USDT)',
    estShares: 'Est. Shares:',
    fee: 'Fee (0.1%):',
    totalToPay: 'Total to Pay:',
    confirmSell: 'Confirm Sell Order',
    ownedShares: 'Owned: {num} Shares',
    sharesToSell: 'Shares to Sell',
    grossValue: 'Gross Value:',
    netReceive: 'Net Receive:',
    orderExecuted: 'Order executed successfully!',
    insufficientBalance: 'Insufficient USDT balance!',
    insufficientShares: 'You do not own enough shares!',
    lightMode: 'Light Mode',
    darkMode: 'Dark Mode',
    shareAndEarn: 'Invite Friends & Earn Rewards',
    referralText: 'Share your code and get 1.5% of their first asset purchase.',
    referralCode: 'Copy referral code',
    copied: 'Copied!',
    marketStatus: 'Market Status: Open',
    vol24h: 'Vol 24h: $4.2M',
    nodesActive: 'Nodes: Active',
    rightsReserved: 'All rights reserved.',
    termsAndConditions: 'Terms & Conditions',
    onlineSupport: 'Online Support',
    demoAccount: 'Demo Account Info',
    demoTip: 'Enter demo / 1234 to login and trade',
    welcomeBack: 'Welcome back,',
    enterAmount: 'Please enter a valid amount',
    home: 'Home',
    homeHeroTitle: 'Invest in Tokenized Real-World Assets (RWA)',
    homeHeroSubtitle: 'AssetChain allows you to buy fractional shares of physical gold, high-grade metals, real estate, and global blue-chip stocks with fully regulated, auditable blockchain smart contracts.',
    homeExploreBtn: 'Explore Markets',
    homeLearnMoreBtn: 'How it Works',
    homeFeatureTitle: 'Why AssetChain?',
    homeFeatureSubtitle: 'The next generation of asset ownership on-chain',
    homeFeature1Title: '100% Physical Backing',
    homeFeature1Desc: 'Every single token on AssetChain represents real, audited physical assets held safely in bank vaults and secure reserves.',
    homeFeature2Title: 'Fractional Ownership',
    homeFeature2Desc: 'Start investing with as little as 1 USDT. Access high-value real estate and luxury commodities without needing millions.',
    homeFeature3Title: 'Institutional Security',
    homeFeature3Desc: 'Regulated structures, multi-signature trust funds, and fully transparent on-chain auditing verify all active reserves.',
    homeFeature4Title: 'Instant Liquidity',
    homeFeature4Desc: 'No lock-ups. Trade your tokenized shares 24/7 on our high-performance decentralised trading engine with immediate USDT settlements.',
    homeHowItWorksTitle: 'Three Steps to On-Chain Wealth',
    homeHowStep1: '1. Deposit USDT',
    homeHowStep1Desc: 'Deposit USDT securely via TRC20, ERC20 or BEP20 networks.',
    homeHowStep2: '2. Choose Your Asset',
    homeHowStep2Desc: 'Explore our diverse marketplace containing metals, real estate, automotive, and global companies.',
    homeHowStep3: '3. Earn & Grow',
    homeHowStep3Desc: "Watch your token's physical value rise or benefit from physical rental and staking yields paid automatically."
  },
  fa: {
    appName: 'AssetChain',
    tagline: 'پلتفرم توکنایزیشن دارایی‌های دنیای واقعی (RWA)',
    statusConnected: 'شبکه اصلی متصل است',
    connectWallet: 'اتصال کیف پول',
    disconnectWallet: 'قطع اتصال',
    assetsMarket: 'بازار دارایی‌ها',
    portfolio: 'پورتفولیو',
    wallet: 'کیف پول',
    history: 'تاریخچه',
    support: 'پشتیبانی',
    aboutUs: 'درباره ما',
    contactUs: 'ارتباط با ما',
    signIn: 'ورود',
    signOut: 'خروج',
    signUp: 'ثبت‌نام',
    usernameOrEmail: 'نام کاربری یا ایمیل',
    password: 'رمز عبور',
    loginError: 'نام کاربری یا رمز عبور اشتباه است (demo / 1234)',
    noAccount: 'حساب کاربری ندارید؟ ثبت‌نام کنید',
    hasAccount: 'قبلاً ثبت‌نام کرده‌اید؟ وارد شوید',
    allMarkets: 'همه بازارها',
    categoryMetals: 'فلزات اساسی',
    categoryAuto: 'خودرو',
    categoryPetro: 'پتروشیمی',
    categoryBank: 'بانکی',
    categoryGlobal: 'سهام جهانی',
    categoryRealEstate: 'املاک و مستغلات',
    categoryCommodities: 'طلا و کالاها',
    statTvl: 'ارزش کل قفل شده (TVL)',
    statApy: 'میانگین سود سالانه',
    statSold: 'دارایی‌های فروخته شده',
    topInvestment: 'برترین فرصت‌های سرمایه‌گذاری RWA',
    tokenPrice: 'قیمت هر توکن',
    expectedYield: 'تخمین رشد / سود سالانه',
    saleProgress: 'پیشرفت فروش',
    remainingUnits: 'موجودی باقیمانده',
    viewDetails: 'مشاهده جزئیات',
    buyNow: 'خرید فوری',
    buy: 'خرید',
    sell: 'فروش',
    myPortfolio: 'پورتفولیو شما',
    totalBalance: 'موجودی کل دارایی‌ها',
    totalPnl: 'سود/زیان کل',
    recentMonth: 'ماه اخیر',
    pnlLabel: 'سود و زیان',
    avgCost: 'میانگین خرید:',
    currentPrice: 'قیمت روز:',
    depositUsdt: 'واریز تتر (USDT)',
    withdrawUsdt: 'برداشت تتر (USDT)',
    transactionWarning: 'تایید و پردازش کلیه تراکنش‌ها ممکن است تا ۲۴ ساعت زمان ببرد.',
    selectNetwork: 'انتخاب شبکه',
    depositAddress: 'آدرس واریز',
    txidLabel: 'هش تراکنش (TxID)',
    txidPlaceholder: 'کد هش تراکنش (TxID) را وارد کنید...',
    submitDeposit: 'ثبت واریزی',
    depositSuccess: 'هش تراکنش ثبت شد! در انتظار تایید ۲۴ ساعته سیستم.',
    destinationAddress: 'آدرس کیف پول مقصد',
    destinationPlaceholder: 'آدرس کیف پول مقصد را وارد کنید...',
    amountUsdt: 'مبلغ تتر (USDT)',
    minAmount: 'حداقل ۱۰ تتر',
    requestWithdraw: 'درخواست برداشت',
    withdrawSuccess: 'درخواست برداشت ثبت شد! واریز تا ۲۴ ساعت آینده.',
    transactionHistory: 'تاریخچه تراکنش‌ها',
    thType: 'نوع و دارایی',
    thAmount: 'مبلغ',
    thDate: 'تاریخ',
    thStatus: 'وضعیت',
    statusCompleted: 'تکمیل شده',
    statusPending: 'در انتظار تایید',
    supportCenter: 'مرکز پشتیبانی',
    describeIssue: 'مشکل خود را توضیح دهید',
    howCanHelp: 'چگونه می‌توانیم به شما کمک کنیم؟',
    submitTicket: 'ثبت تیکت',
    ticketSuccess: 'تیکت شماره {num} ثبت شد! حداکثر تا ۷۲ ساعت آینده پاسخ داده خواهد شد.',
    confirmBuy: 'تایید سفارش خرید',
    amountToInvest: 'مبلغ سرمایه‌گذاری (USDT)',
    estShares: 'تعداد سهم تقریبی:',
    fee: 'کارمزد (۰.۱٪):',
    totalToPay: 'پرداختی کل:',
    confirmSell: 'تایید سفارش فروش',
    ownedShares: 'موجودی: {num} سهم',
    sharesToSell: 'تعداد سهم برای فروش',
    grossValue: 'ارزش کل فروش:',
    netReceive: 'دریافتی خالص:',
    orderExecuted: 'سفارش با موفقیت انجام شد!',
    insufficientBalance: 'موجودی تتر کافی نیست!',
    insufficientShares: 'سهم کافی برای فروش ندارید!',
    lightMode: 'حالت روشن',
    darkMode: 'حالت تاریک',
    shareAndEarn: 'دعوت از دوستان و دریافت جایزه',
    referralText: 'کد دعوت خود را به اشتراک بگذارید و ۱.۵٪ از اولین خرید دارایی دوستانتان هدیه بگیرید.',
    referralCode: 'کپی کد معرف',
    copied: 'کپی شد!',
    marketStatus: 'وضعیت بازار: باز',
    vol24h: 'حجم ۲۴ ساعته: ۴.۲ میلیون دلار',
    nodesActive: 'گره‌ها: فعال',
    rightsReserved: 'تمامی حقوق محفوظ است.',
    termsAndConditions: 'قوانین و مقررات',
    onlineSupport: 'پشتیبانی آنلاین',
    demoAccount: 'اطلاعات حساب کاربری دمو',
    demoTip: 'برای ورود و معامله از نام کاربری demo و رمز عبور 1234 استفاده کنید',
    welcomeBack: 'خوش آمدید،',
    enterAmount: 'لطفاً مبلغ معتبری وارد کنید',
    home: 'صفحه اصلی',
    homeHeroTitle: 'سرمایه‌گذاری در دارایی‌های دنیای واقعی (RWA)',
    homeHeroSubtitle: 'AssetChain به شما امکان می‌دهد تا سهم‌های خرد شده‌ای از طلای فیزیکی، فلزات اساسی، املاک و مستغلات، و سهام‌های معتبر جهانی را با قراردادهای هوشمند بلاکچینی قانون‌گذاری‌شده و قابل حسابرسی خریداری کنید.',
    homeExploreBtn: 'ورود به بازارها',
    homeLearnMoreBtn: 'چگونه کار می‌کند؟',
    homeFeatureTitle: 'چرا AssetChain؟',
    homeFeatureSubtitle: 'نسل بعدی مالکیت دارایی‌ها روی زنجیره',
    homeFeature1Title: '۱۰۰٪ پشتوانه فیزیکی واقعی',
    homeFeature1Desc: 'تک تک توکن‌ها در AssetChain نماینده دارایی‌های فیزیکی واقعی و حسابرسی‌شده‌ای هستند که در خزانه‌های بانکی و ذخایر امن نگهداری می‌شوند.',
    homeFeature2Title: 'مالکیت خرد شده و ارزان',
    homeFeature2Desc: 'شروع سرمایه‌گذاری با حداقل ۱ تتر. بدون نیاز به میلیون‌ها دلار، به املاک لوکس و کالاهای گران‌بها دسترسی داشته باشید.',
    homeFeature3Title: 'امنیت در سطح سازمانی',
    homeFeature3Desc: 'ساختارهای تحت نظارت، صندوق‌های امانی چندامضایی، و حسابرسی شفاف درون‌زنجیره‌ای، تمامی ذخایر فعال را تایید می‌کنند.',
    homeFeature4Title: 'نقدشوندگی آنی و سریع',
    homeFeature4Desc: 'بدون دوره بلوکه شدن. دارایی‌های توکنایز شده خود را ۲۴ ساعته در موتور معاملاتی فوق‌سریع ما معامله کنید و آنی تسویه تتر بگیرید.',
    homeHowItWorksTitle: '۳ مرحله ساده برای مالکیت دارایی‌های واقعی',
    homeHowStep1: '۱. شارژ حساب تتر',
    homeHowStep1Desc: 'حساب خود را به صورت امن با تتر از طریق شبکه‌های TRC20، ERC20 یا BEP20 شارژ کنید.',
    homeHowStep2: '۲. انتخاب دارایی دلخواه',
    homeHowStep2Desc: 'بازار متنوع ما شامل فلزات، املاک، خودرو و شرکت‌های بزرگ جهانی را بررسی و دارایی مورد نظر را انتخاب کنید.',
    homeHowStep3: '۳. دریافت سود و رشد',
    homeHowStep3Desc: 'رشد ارزش دارایی فیزیکی خود را مشاهده کنید یا از اجاره‌بها و سودهای پرداختی بهره‌مند شوید.'
  }
};
